name: Clojure CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Java and Leiningen
      uses: DeLaGuardo/setup-clojure@v12 # Use the latest version
      with:
          java-version: 17 # Specify the desired Java version
          lein: 2.11.2 # Specify the desired Leiningen version
    - name: Run tests
      run: lein test
